### ISSUE TITLE
Alternatives

### ISSUE THREAD

**Issue by kaihendry** [Fmstrat/nowgallery#1]
Sorry, randomly came across this project since I looking at diy-ipmi. Since there is no email address in your git repo, and using this issue to express some feedback.

I implemented something similar in Golang https://github.com/kaihendry/lk2

I prefer a static binary over a docker image ;)

**Comment by Fmstrat** [comment]
Ahh, nice. I've debated on starting up some Go projects. You can reach me at https://twitter.com/Fmstrat
